my-node-app:
  image: sammons/my-node-app
  environment:
    - NODE_ENV=docker
  volumes:
  # my-machine-path : path-inside-image
    - .:/usr/src/app
  ports:
  # port inside container : port in vm
    - "3900:3900"
  links:
  # DNS resolve postgres to wherever postgres is
  # note, without net: host 127.0.0.1 will not work for
  # containers
   - postgres

my-cloj-app:
  image: sammons/my-cloj-app
  volumes:
    - .:/usr/src/app
  ports:
    - "4000:4000"
  links:
   - postgres

postgres:
  image: postgres
  ports:
    - "5432:5432"